import Head from "next/head";

export function Header(props: { page?: string }) {
  let pageTitle: string = "Jeff's Home";
  if (props.page) {
    pageTitle += " - " + props.page;
  }
  return (
    <Head>
      <title>{pageTitle}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* <script
        type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/emailjs-com@3/dist/email.min.js"
      ></script> */}
    </Head>
  );
}
